findAnimal/findAnimal/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^findAnimalApp/', include('findAnimalApp.urls')),
    url(r'^admin/', admin.site.urls),
]

findAnimal/findAnimalApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'findAnimalApp'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<notice_id>[0-9]+)/$',views.notice,name="notice"),
    url(r'^new_notice/$',views.create_notice,name="create_notice"),
   #url(r'^edit_notice/(?P<notice_id>[0-9]+)/$',views.edit_notice,name="edit_notice"),
]

findAnimal/findAnimalApp/models.py
from _ast import mod

from django.db import models


# Create your models here.
class NoticeCategory(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Location (models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,null=True,default=None,blank=True)

    def __str__(self):
        result = self.name
        if self.parent:
            result += ', ' + self.parent.__str__()
        return result


class Animal (models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Breed (models.Model):
    name = models.CharField(max_length=50)
    id_animal = models.ForeignKey(Animal,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Notice (models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)
    id_animal = models.ForeignKey(Animal,on_delete=models.CASCADE)
    id_location = models.ForeignKey(Location,on_delete=models.CASCADE)
    id_breed = models.ForeignKey(Breed,on_delete=models.CASCADE)
    id_category = models.ForeignKey(NoticeCategory,on_delete=models.CASCADE)
    owner_email = models.EmailField(max_length=50)

    def __str__(self):
        return self.title


class Photo (models.Model):
    id_notice = models.ForeignKey(Notice,on_delete=models.CASCADE)
    picture = models.ImageField(default=None,upload_to="images")

    def get_url(self):
        return "findAnimalApp/" + self.picture.url


class Comment (models.Model):
    id_notice = models.ForeignKey(Notice,on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.author + ': ' + self.text


class Change (models.Model):
    id_notice = models.ForeignKey(Notice,on_delete=models.CASCADE)
    activity = models.DateTimeField()
    key = models.CharField(max_length=10)

findAnimal/findAnimalApp/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Notice, Comment, Photo

class NoticeForm(ModelForm):
    class Meta:
        model = Notice
        fields = ['id_category', 'title', 'text', 'id_animal', 'id_breed', 'id_location','owner_email']
        widgets = {
            'text': Textarea(attrs={'cols': 80, 'rows': 10}),
        }
        labels = {
            'title':('Заголовок'),
            'text':('Текст'),
            'id_animal':('Животное'),
            'id_category':('Категория'),
            'id_breed':('Порода'),
            'id_location':('Место'),
            'owner_email':('Email владельца'),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'text', 'email']
        widgets = {
            'text': Textarea(attrs={'cols': 80, 'rows': 5}),
            'id_notice': forms.HiddenInput(),
        }
        labels = {
            'author': 'Автор',
            'text': 'Текст',
            'email': 'E-mail'
        }

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['picture']
        labels = {
            'picture': 'Фото',
        }

findAnimal/findAnimalApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.core.files.uploadedfile import SimpleUploadedFile

from .models import Comment, Change, NoticeCategory, Breed, Animal, Location, Notice, Photo
from .forms import NoticeForm,CommentForm,PhotoForm


# Create your views here.
def index(request):
    notices_list = Notice.objects.order_by('title')
    context = {
        'notices_list': notices_list,
    }
    #output = ' '.join([n.title for n in notices_list])
    return render(request,'findAnimalApp/index.html',context)


def notice(request,notice_id):
    notice_obj = get_object_or_404(Notice, pk=notice_id)
    photo = Photo.objects.filter(id_notice=notice_obj)[:1]
    if photo:
        photo = photo.get()
    else:
        photo = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            newComment = form.save(commit=False)
            newComment.id_notice = notice_obj
            newComment.save()
    comments = Comment.objects.filter(id_notice=notice_obj)
    commentForm = CommentForm()
    context={
        'notice': notice_obj,
        'comments': comments,
        'addcomment': commentForm,
        'photo': photo
    }
    return render(request,"findAnimalApp/notice.html",context)

def create_notice(request):
    if request.method == 'POST':
        form = NoticeForm(request.POST)
        photo = PhotoForm(request.POST,request.FILES)
        if form.is_valid():
            new_notice = form.save()
        if photo.is_valid():
            photo_i = photo.save(commit=False)
            photo_i.id_notice = new_notice
            photo_i.save()
        return HttpResponseRedirect('/findAnimalApp/'+new_notice.id.__str__())
    elif 'notice_id' in request.GET:
            notice_id = request.GET['notice_id']
            notice = get_object_or_404(Notice, pk=notice_id)
            form = NoticeForm(instance=notice)
            photo = Photo.objects.filter(id_notice = notice)[:1]
            if photo:
                photo = PhotoForm(instance=photo.get())
            else:
                photo = PhotoForm()
    else:
        form = NoticeForm()
        photo = PhotoForm()
    return render(request, "findAnimalApp/create_notice.html", {'form': form, 'photo': photo})

# def edit_notice(request,notice_id):
#     notice = get_object_or_404(Notice, pk=notice_id)
#     form = NoticeForm(request.POST,notice)

findAnimal/findAnimalApp/templates/findAnimalApp/create_notice.html
{% extends "findAnimalApp/menu.html" %}
{% block content %}
{% load staticfiles %}
<form enctype="multipart/form-data" action="{% url 'findAnimalApp:create_notice' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if photo.instance.picture %}
        <img src= {% static photo.instance.get_url %}>
    {% endif %}
    {{ photo.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

findAnimal/findAnimalApp/templates/findAnimalApp/index.html
{% extends "findAnimalApp/menu.html" %}

{% block content %}
<h1>Объявления</h1>
{% if notices_list %}
    <ul>
    {% for notice in notices_list %}
        <li><a href="{% url 'findAnimalApp:notice' notice.id %}">{{ notice.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No notices are available.</p>
{% endif %}
{% endblock %}

findAnimal/findAnimalApp/templates/findAnimalApp/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'findAnimalApp/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'findAnimalApp/css/custom.css' %}" />
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
<div class="container">
    <div class="row">
    <div class="col-md-2" id="menu">
        {% block sidebar %}
        <div class="sidebar-offcanvas" id="sidebar" role="navigation">
            <ul class="nav nav-pills nav-stacked">
                <li class="nav-item"><a class="nav-link" href="/findAnimalApp/">Главная</a></li>
                <li class="nav-item"><a class="nav-link" href="/findAnimalApp/new_notice/">Добавить объявление</a></li>
                </ul>
        </div>
        {% endblock %}
    </div>

    <div id="content" class="col-md-10">
        {% block content %}{% endblock %}
    </div>
        </div>
    </div>
</body>
    <script href="{% static 'findAnimalApp/bootstrap-3.3.6-dist/js/bootstrap.min.js' %}" />
</html>

findAnimal/findAnimalApp/templates/findAnimalApp/notice.html
{% extends "findAnimalApp/menu.html" %}

{% block content %}
{% load staticfiles %}
<p><label>Заголовок: </label> <div>{{notice.title}}</div></p>
<p><label>Категория: </label> <div>{{notice.id_category.name}}</div></p>
<p><label>Текст: </label> <div>{{notice.text}} </div> </p>
<p><label>Животное: </label> <div> {{notice.id_animal.name}} </div> </p>
<p><label>Порода: </label> <div> {{notice.id_breed.name}} </div> </p>
<p><label>Место: </label> <div> {{notice.id_location.name}} </div> </p>
<p><label>Почта владельца: </label> <div> {{notice.owner_email}}</div> </p>
{% if photo %}
<p><label>Фото: </label> <div><img src= {% static photo.get_url %}></div> </p>
{% endif %}
<br/><br/>
<button type="button" class="btn btn-primary">
    <a href="{% url 'findAnimalApp:create_notice'%}?notice_id={{notice.id}}">
        Редактировать
    </a>
</button>
<br/><br/>
<div id="commentsBlock">
<h3>Комментарии:</h3>
{% if comments %}
    <ul>
    {% for comment in comments %}
        <li>
            <p><label>{{comment.author}}:</label>
            {{comment.text}}</p>
        </li>
    {% endfor %}
    </ul>
{% else %}
<p>No comments</p>
{% endif %}
    </div>
<form action="" method="post">
    {% csrf_token %}
    {{ addcomment.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}